#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Daemon for controlling a Physik Instrumente C-863 focus controller via Pyro"""

import argparse
import datetime
import serial
import threading
import time
import traceback
import sys
import Pyro4
from astropy.time import Time
import astropy.units as u
from rockit.common import log, TryLock
from rockit.common.helpers import pyro_client_matches
from rockit.focuser.c863 import CommandStatus, Config, ServoState


class C863FocuserDaemon:
    """Daemon interface for Physik Instrumente C-863 focus controller"""
    def __init__(self, config):
        self._command_lock = threading.Lock()
        self._config = config

        self._port = None
        self._port_error = False

        self._state = ServoState.Disabled
        self._current_steps = 0
        self._target_steps = 0
        self.wait_condition = threading.Condition()

        threading.Thread(target=self.__run, daemon=True).start()


    def __run(self):
        """Background thread managing communication over the serial connection"""
        while True:
            # TODO
            with self.wait_condition:
                self.wait_condition.wait(10)

    @Pyro4.expose
    def report_status(self):
        """Returns a dictionary containing the current focuser state"""
        with self._status_lock:
            return {
                'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
                'state': self._state,
                'state_label': ServoState.label(self._state),
                'current_steps': self._current_steps,
                'target_steps': self._target_steps
            }

    @Pyro4.expose
    def move(self, steps, relative=True):
        """Request a to move a specific step position"""
        if not pyro_client_matches(self.config.control_ips):
            return CommandStatus.InvalidControlIP

        # TODO
        return CommandStatus.Failed

    @Pyro4.expose
    def stop(self):
        """Stop any in progress movement"""
        if not pyro_client_matches(self.config.control_ips):
            return CommandStatus.InvalidControlIP

        # TODO
        return CommandStatus.Failed

    @Pyro4.expose
    def initialize(self):
        """Connects to the device"""
        if not pyro_client_matches(self._config.control_ips):
            return CommandStatus.InvalidControlIP

        with TryLock(self._command_lock) as success:
            if not success:
                return CommandStatus.Blocked

            if self._port is not None:
                return CommandStatus.NotDisconnected

            port = None
            try:
                port = serial.Serial(self._config.serial_port,
                                     self._config.serial_baud,
                                     timeout=self._config.serial_timeout)
                log.info(self._config.log_name, 'connected to focuser')

                # Flush any stale state
                port.flushInput()
                port.flushOutput()

                def send(cmd):
                    if port.write(cmd.encode('ascii')) != len(cmd):
                        raise serial.SerialException(f'Failed to send command')

                # Select default controller
                send('\x010')

                # Enable servo and adjust PID D term
                send('MN\r')
                send('DP350\r')

                # Find home
                send('FE2\r')
                send('WS0,DH\r')

                # Wait for it to stop moving
                start = Time.now()
                while True:
                    send('\\')
                    status = port.read(4)
                    if status[0] == 48:
                        break

                    if Time.now() - start > self._config.move_timeout * u.s:
                        raise TimeoutError('Timeout while homing')

                    time.sleep(0.1)

                log.info(self._config.log_name, 'Focuser initialized')

                return CommandStatus.Succeeded
            except:
                print('error while initializing focuser')
                traceback.print_exc(file=sys.stdout)
                if port:
                    port.close()
                return CommandStatus.Failed


    @Pyro4.expose
    def shutdown(self):
        """Disconnects from the focuser hardware"""
        if not pyro_client_matches(self.config.control_ips):
            return CommandStatus.InvalidControlIP

        # TODO
        return CommandStatus.Failed


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Servo controller server')
    parser.add_argument('config', help='Path to configuration json file')
    args = parser.parse_args()
    _config = Config(args.config)
    _config.daemon.launch(C863FocuserDaemon(_config))
